//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int personId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string roleCode { get; set; }
        public int loginAttempts { get; set; }
        public bool isLocked { get; set; }

        public virtual Person Person { get; set; }
        public virtual Role Role { get; set; }
    }
}