//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int cartDetailId { get; set; }
        public int personId { get; set; }
        public int gameDetaild { get; set; }
        public int quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual GameDetail GameDetail { get; set; }
    }
}
