//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlatform
    {
        public int gamePlatformId { get; set; }
        public int gameId { get; set; }
        public string platformCode { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Platform Platform { get; set; }
    }
}
