//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailId { get; set; }
        public int orderId { get; set; }
        public int gameDetailId { get; set; }
        public int quantity { get; set; }
        public decimal uPrice { get; set; }
    
        public virtual GameDetail GameDetail { get; set; }
        public virtual Order Order { get; set; }
    }
}
