//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPlatform
    {
        public int personPlatformId { get; set; }
        public int personId { get; set; }
        public string platformCode { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Platform Platform { get; set; }
    }
}
